---
- name: install mysql
  yum: pkg={{ item }} state=present
  with_items:
    - mysql
    - mysql-server
    - mysql-utilities

- template: src=my.cnf dest=/etc/my.cnf

- name: start RDB
  service: name=mysqld state=started enabled=yes

- mysql_db: name=beppu state=present

- mysql_user: name={{ item.name }} state=present password={{ item.password }} host={{ item.host }} priv={{ item.priv }}
  with_items:
    - { name: "beppu", password: "beppu", host: "%",         priv: "pikachi.*:ALL" }
    - { name: "beppu", password: "beppu", host: "localhost", priv: "pikachi.*:ALL" }
    - { name: "beppu", password: "beppu", host: "127.0.0.1", priv: "pikachi.*:ALL" }
